### ISSUE TITLE
Random Fatal Error on Edit Entry when using a survey field

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1743]
![image](https://user-images.githubusercontent.com/1222472/188983625-cda3ef85-566c-43fd-b506-5025bdca55b2.png)

```
Fatal error: Uncaught TypeError: floor(): Argument #1 ($num) must be of type int|float, string given in /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-survey.php:123 Stack trace: #0 /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-survey.php(123): floor('id') 

>#1 /home/userwebsite/public_html/sis/wp-includes/class-wp-hook.php(309): GravityView_Plugin_Hooks_Gravity_Forms_Survey->fix_survey_field_value('', Object(GF_Field_Likert), 'glikertrow20aa8...') 
#2 /home/userwebsite/public_html/sis/wp-includes/plugin.php(191): WP_Hook->apply_filters('', Array) 
#3 /home/userwebsite/public_html/sis/wp-content/plugins/gravityforms/gravityforms.php(7009): apply_filters('gform_field_val...', '', Object(GF_Field_Likert), 'glikertrow20aa8...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) 
#4 /home/userwebsite/public_html/sis/wp-content/plugins/gravityforms/forms_model.php(4285): gf_apply_filters('gform_field_val...', '', Object(GF_Field_Likert), 'glikertrow20aa8...') 
#5 /home/userwebsite/public_html/sis/wp-content/plugins/gravityforms/includes/fields/class-gf-field.php(868): GFFormsModel::get_parameter_value('glikertrow20aa8...', Array, Object(GF_Field_Likert)) 
#6 /home/userwebsite/public_html/sis/wp-content/plugins/gravityforms/includes/fields/class-gf-field.php(840): GF_Field->get_input_value_submission('input_1_1', 'glikertrow20aa8...', Array, true) 
#7 /home/userwebsite/public_html/sis/wp-content/plugins/gravityforms/forms_model.php(3757): GF_Field->get_value_submission(Array, true) 
#8 /home/userwebsite/public_html/sis/wp-content/plugins/gravityforms/form_display.php(1132): GFFormsModel::get_field_value(Object(GF_Field_Likert), Array) 
#9 /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-render.php(1346): GFFormDisplay::get_form(29, false, false, true, Array) 
#10 /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-render.php(1120): GravityView_Edit_Entry_Render->render_edit_form() 
#11 /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-render.php(309): GravityView_Edit_Entry_Render->edit_entry_form() 
#12 /home/userwebsite/public_html/sis/wp-includes/class-wp-hook.php(307): GravityView_Edit_Entry_Render->init(Object(GravityView_View_Data), Object(GV\GF_Entry), Object(GV\View), Object(GV\Frontend_Request)) 
#13 /home/userwebsite/public_html/sis/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) 
#14 /home/userwebsite/public_html/sis/wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#15 /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/future/includes/class-gv-renderer-entry-edit.php(40): do_action('gravityview_edi...', NULL, Object(GV\GF_Entry), Object(GV\View), Object(GV\Frontend_Request)) 
#16 /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/future/includes/class-gv-view.php(353): GV\Edit_Entry_Renderer->render(Object(GV\GF_Entry), Object(GV\View), Object(GV\Frontend_Request)) 
#17 /home/userwebsite/public_html/sis/wp-includes/class-wp-hook.php(307): GV\View::content('') 
#18 /home/userwebsite/public_html/sis/wp-includes/plugin.php(191): WP_Hook->apply_filters('', Array) 
#19 /home/userwebsite/public_html/sis/wp-includes/post-template.php(253): apply_filters('the_content', '') 
#20 /home/userwebsite/public_html/sis/wp-content/themes/salient/includes/partials/single-post/post-content.php(112): the_content('<span class="co...') 
#21 /home/userwebsite/public_html/sis/wp-includes/template.php(772): require('/home/userwebs...') 
#22 /home/userwebsite/public_html/sis/wp-includes/template.php(716): load_template('/home/userwebs...', false, Array) 
#23 /home/userwebsite/public_html/sis/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) 
#24 /home/userwebsite/public_html/sis/wp-content/themes/salient/single.php(100): get_template_part('includes/partia...') 
#25 /home/userwebsite/public_html/sis/wp-includes/template-loader.php(106): include('/home/userwebs...') 
#26 /home/userwebsite/public_html/sis/wp-blog-header.php(19): require_once('/home/userwebs...') 
#27 /home/userwebsite/public_html/sis/index.php(17): require('/home/userwebs...') 
#28 {main} thrown in /home/userwebsite/public_html/sis/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-survey.php on line 123
```

Replacing the `floor()` check for an `(int)`  casting did the trick:

Couldn't replicate on the `debug` website with the user's form export: https://debug.gravityview.co/view/survey-likert-with-multiple-choices/entry/20455/?edit=a5501a1356&gvid=2343

Tested with: GV 2.14.7, GF2 2.6.6, Survey add-on 3.7
[Downloads.zip](https://github.com/gravityview/GravityView/files/9515551/Downloads.zip)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2001746021/43323

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2043659072/44249
