### ISSUE TITLE
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Only gravityview post types can be \GV\View instances.'

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#870]
Social Sharing & SEO Extension causes conflict.

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Only gravityview post types can be \GV\View instances.' in 
[...]/wp-content/plugins/gravityview/future/includes/class-gv-view.php:189 Stack trace: 
#0 [...]/wp-content/plugins/gravityview/future/includes/class-gv-view.php(295): GV\View::from_post(Object(WP_Post)) 
#1 [...]/wp-content/plugins/gravityview/includes/class-api.php(1014): GV\View::by_id(NULL) 
#2 [...]/wp-content/plugins/gravityview-sharing-seo/sharing-common-functions.php(23): gravityview_get_current_view_data(NULL) 
#3 [...]/wp-content/plugins/gravityview-sharing-seo/includes/class-gravityview-social-meta.php(137): gravityview_social_get_title('Network') 
#4 [internal function]: GravityView_Social_Meta->jetpack_opengraph_filter(Array, Array) 
#5 [...]/wp-includes/class-wp-hook.php(298): call_u in [...]/wp-content/plugins/gravityview/future/includes/class-gv-view.php on line 189
```

**Comment by zackkatz** [comment]
This was fixed in 1.21.4
